# Software for all engineering new hires
base_cask_list:
  - docker
  - iterm2 # Terminal Emulator
  - lastpass
  - rectangle # Window snapping!
base_package_list:
  - ansible # To run this playbook
  - gh # Github CLI tool
  - awscli # AWS API CLI tool
  - diff-so-fancy # Additional diff options with Git
  - docker-compose
  - ghq # Additional Git CLI tool for managing repos
  - htop # Performance and process monitor
  - jq # Json parser
  - pre-commit # Runs hooks against Git commits to enforce standards
  - tmux # Virtual terminal tool
  - vault # Hashicorp's secret manager
  - yq # Yaml parser
  - bash # Update bash from 3.2 to 5.x to fix this https://github.com/antonbabenko/pre-commit-terraform/issues/337
  - norwoodj/tap/helm-docs # helm chart documentation generator, used with pre-commit
  - terraform-docs # terraform documentation generator, used with pre-commit
  - hadolint # Dockerfile linter

# Optional packages for k8s and terraform
k8s_package_list:
  - helm
  - helmfile
  - kubectx
  - ansible-lint
  - k9s
  - krew
  - kubectl
  - kustomize
  - argocd

tf_package_list:
  - tflint
  - tfenv
