---
- name: homebrew | Install k8s packages
  community.general.homebrew:
    name: "{{ k8s_package_list }}"

- name: file | Create needed directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
  loop:
    - path: ~/.kube
    - path: ~/.kube/configs

- name: shell | Add krew repos
  ansible.builtin.command: "kubectl krew index add {{ item.name }} {{ item.url }}"
  args:
    creates: "~/.krew/index/{{ item.name }}"
  loop:
    - { name: kvaps, url: https://github.com/kvaps/krew-index }
    - { name: default, url: https://github.com/kubernetes-sigs/krew-index }

- name: shell | Install kubectl plugins
  ansible.builtin.command: "kubectl krew install {{ item.receipt }}"
  args:
    creates: "~/.krew/receipts/{{ item.name }}.yaml"
  loop:
    - { name: node-shell, receipt: kvaps/node-shell }
    - { name: get-all, receipt: get-all }

- name: shell | Install helm plugins
  ansible.builtin.command: "helm plugin install {{ item.url }}{% if item.version|d(False) %} --version {{ item.version }}{% endif %}"
  args:
    creates: "~/Library/helm/plugins/{{ item.name }}"
  #  community.kubernetes.helm_plugin:
  #    plugin_path: https://github.com/adamreese/helm-env
  #    state: present
  loop:
    - {
        name: helm-diff,
        url: https://github.com/databus23/helm-diff,
        version: v3.6.0,
      }
    - {
        name: helm-git,
        url: https://github.com/aslafy-z/helm-git,
        version: 0.10.0,
      }
